@HostAddress = http://localhost:5157

# Retrieves all users.
GET {{HostAddress}}/users/
Accept: application/json

###

# Adds a new user 
POST {{HostAddress}}/users/
Content-Type: application/json

{
    "userId": "1902c6a2-7549-4eb5-bcb1-29be91d4a74e",
    "firstName": "Master",
    "lastName": "Yoda"
}

###

# Updates an existing user
PUT {{HostAddress}}/users/87d713b2-ffcf-4ba0-b5ba-3de1109a642c
Content-Type: application/json

{
    "userId": "87d713b2-ffcf-4ba0-b5ba-3de1109a642c",
    "firstName": "Darth",
    "lastName": "Vader"
}

###

# Deletes a user
DELETE {{HostAddress}}/users/1902c6a2-7549-4eb5-bcb1-29be91d4a74e